[project]
name = "yenslife-rss-feed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.27.0",
    "toml>=0.10.2",
    "sqlalchemy>=2.0.45",
    "flet>=0.28.3",
]
